version: "3"
services:
  api:
    build:
      context: ./tatpapers-core
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: api
    ports:
      - "8000:8000"
    volumes: 
      - ./tatpapers-core:/code

  web:
    build:
      context: ./tatpapers-web
      dockerfile: Dockerfile.dev
    container_name: web
    ports: 
      - "3000:3000"
    volumes: 
      - ./tatpapers-web:/app
      - node_modules:/app/node_modules
    stdin_open: true
  
  db:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qazwsx
    volumes:
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data:
  node_modules: